

nelmio_cors:
    defaults:
        origin_regex: true
#        allow_credentials: false
#        allow_origin: ['%cors_allow_origin%']
        allow_origin: ['*']
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Content-Type', 'Authorization' ]
        expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
        max_age: 3600
        hosts: []
#        forced_allow_origin_value: ~
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['https://master-7rqtwti-7rmsoyfng4yww.fr-3.platformsh.site'] # You probably want to change this regex to match your real domain
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Link' ]
            max_age: 3600
        '^/api/':
            origin_regex: true
            allow_origin: ['https://master-7rqtwti-7rmsoyfng4yww.fr-3.platformsh.site'] # You probably want to change this regex to match your real domain
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Link' ]
            max_age: 3600
        '^/api/docs/':
            origin_regex: true
            allow_origin: ['https://master-7rqtwti-7rmsoyfng4yww.fr-3.platformsh.site'] # You probably want to change this regex to match your real domain
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Link' ]
            max_age: 3600
