

nelmio_cors:
    defaults:
        origin_regex: true
#        allow_credentials: false
        allow_origin: ['%env(resolve:CORS_ALLOW_ORIGIN)%']
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Content-Type', 'Authorization' ]
        expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api':
            origin_regex: true
            allow_origin: [ '%env(resolve:CORS_ALLOW_ORIGIN)%' ]
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
            max_age: 3600
