parameters:
    cors_allow_origin: '%env(resolve:CORS_ALLOW_ORIGIN)%'

nelmio_cors:
    defaults:
        origin_regex: true
#        allow_credentials: false
#        allow_origin: ['%cors_allow_origin%']
        allow_origin: ['https:\/\/api\.master-7rqtwti.*']
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Content-Type', 'Authorization' ]
        expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
#        '^/api/':
        '^/':
            origin_regex: true
            allow_origin: ['https:\/\/api\.master-7rqtwti.*'] # You probably want to change this regex to match your real domain
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
            max_age: 3600
