

nelmio_cors:
    defaults:
        origin_regex: true
#        allow_credentials: false
        #TODO make it dynamic via config
#        allow_origin: ['%cors_allow_origin%']
        allow_origin: ['^https:\/\/.*7rmsoyfng4yww.fr-3.platformsh.site']
        allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Content-Type', 'Authorization' ]
        expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
#        '^/':
#            origin_regex: true
#            allow_origin: ['^https:\/\/.*7rmsoyfng4yww.fr-3.platformsh.site']
#            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
#            allow_headers: [ 'Content-Type', 'Authorization' ]
#            expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
#            max_age: 3600
        '^/api':
            origin_regex: true
            allow_origin: ['^https:\/\/.*7rmsoyfng4yww.fr-3.platformsh.site']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
            max_age: 3600
#
#        '^/api/':
#            origin_regex: true
#            allow_origin: ['*.7rmsoyfng4yww.fr-3.platformsh.site']
#            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#            allow_headers: ['Content-Type', 'Authorization']
#            expose_headers: [ 'Content-Disposition', 'Content-Length', 'Link' ]
#            max_age: 3600
