mysqldb:
    type: postgresql:13
    disk: 1024
    configuration:
        schemas:
            - main
            # Uncomment if you want to store dfs tables in a separate database:
            #- dfs
        endpoints:
            user:
                default_schema: main
                privileges:
                    main: admin